#!/usr/bin/env python3
"""
Production Training Pipeline on Real Candidate Pairs for ML Challenge 2026.
Trains LightGBM classifier on real candidates generated by blocking (labeled against ground truth),
eliminating train-test distribution shift.

Features:
1. Loads candidate pairs file and ground truth labels (target = 1 if match, 0 if false candidate).
2. Computes 16 vectorized similarity and disqualifier features.
3. Trains LightGBM model with precision calibration.
4. Performs threshold grid search on validation set to maximize Macro F0.5.
5. Saves winning model to output/stage1_lgb_model.txt.
"""

import sys
if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(line_buffering=True, encoding='utf-8', errors='replace')

import os
import time
import argparse
import random
import pandas as pd
import numpy as np
import lightgbm as lgb
from collections import defaultdict

from matching_pipeline import FEATURE_COLUMNS, compute_features_fast
from evaluate_local import compute_macro_f05, print_evaluation_report, load_val_ground_truth

def main():
    start_time = time.time()
    print("=" * 80, flush=True)
    print(" TRAINING LIGHTGBM CLASSIFIER ON REAL BLOCKING CANDIDATE PAIRS", flush=True)
    print("=" * 80, flush=True)

    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    train_dir = os.path.join(base_dir, 'student_resource', 'dataset', 'train')
    data_dir = os.path.join(base_dir, 'data', 'processed')
    output_dir = os.path.join(base_dir, 'output')
    os.makedirs(output_dir, exist_ok=True)

    parser = argparse.ArgumentParser()
    parser.add_argument('--cands-file', type=str, default=None,
                        help="Path to candidate pairs TSV file to train/validate on")
    parser.add_argument('--gt-file', type=str, default=None,
                        help="Path to ground truth TSV file")
    parser.add_argument('--sample-pairs', type=int, default=500000,
                        help="Max candidate pairs to train on (default: 500,000)")
    parser.add_argument('--model-out', type=str, default=os.path.join(output_dir, 'stage1_lgb_model.txt'),
                        help="Output path for trained LightGBM model")
    args = parser.parse_args()

    cands_file = args.cands_file
    if cands_file is None:
        cands_file = os.path.join(data_dir, 'candidate_pairs_val.tsv')
        if not os.path.exists(cands_file):
            cands_file = os.path.join(data_dir, 'candidate_pairs_val_US.tsv')

    gt_file = args.gt_file
    if gt_file is None:
        gt_file = os.path.join(data_dir, 'val_ground_truth.tsv')
        if not os.path.exists(gt_file):
            gt_file = os.path.join(train_dir, 'train_ground_truth.tsv')

    print(f"Candidates file: {cands_file}", flush=True)
    print(f"Ground truth:    {gt_file}", flush=True)
    print(f"Model target:    {args.model_out}", flush=True)

    # 1. Load Ground Truth Mapping
    print("\n[1/5] Loading Ground Truth Labels...", flush=True)
    gt_dict = {}
    with open(gt_file, 'r', encoding='utf-8') as f:
        next(f)
        for line in f:
            p = line.rstrip('\n').split('\t')
            s1 = p[0]
            ms = p[1].split(',') if len(p) > 1 and p[1].strip() else []
            gt_dict[s1] = set(m.strip() for m in ms if m.strip())
    print(f"   -> Loaded ground truth for {len(gt_dict):,} S1 entities.", flush=True)

    # 2. Parse candidate pairs
    print(f"\n[2/5] Parsing candidate pairs from {os.path.basename(cands_file)}...", flush=True)
    raw_pairs = []
    needed_s1 = set()
    needed_cand = set()

    with open(cands_file, 'r', encoding='utf-8') as f:
        next(f)
        for line in f:
            p = line.rstrip('\n').split('\t')
            s1 = p[0]
            if len(p) > 1 and p[1].strip():
                c_list = [c.strip() for c in p[1].split(',') if c.strip()]
                for c2 in c_list:
                    raw_pairs.append((s1, c2))
                    needed_s1.add(s1)
                    needed_cand.add(c2)

    print(f"   -> Total candidate pairs loaded: {len(raw_pairs):,}", flush=True)
    print(f"   -> Unique S1 entities:           {len(needed_s1):,}", flush=True)
    print(f"   -> Unique S2/S3 candidates:      {len(needed_cand):,}", flush=True)

    # Subsample if necessary for fast balanced training
    if len(raw_pairs) > args.sample_pairs:
        random.seed(42)
        sample_pairs = random.sample(raw_pairs, args.sample_pairs)
        print(f"   -> Sampled {len(sample_pairs):,} pairs for training.", flush=True)
    else:
        sample_pairs = raw_pairs

    # 3. Load Attributes from train sources
    print("\n[3/5] Loading entity attributes from train sources...", flush=True)
    t0 = time.time()
    s1_dict = {}
    with open(os.path.join(train_dir, 'train_source1.tsv'), 'r', encoding='utf-8') as f:
        next(f)
        for line in f:
            p = line.rstrip('\n').split('\t')
            if p[0] in needed_s1:
                s1_dict[p[0]] = (
                    p[1] if len(p) > 1 else '',
                    p[2] if len(p) > 2 else '',
                    p[3] if len(p) > 3 else ''
                )

    cand_dict = {}
    for src in ['train_source2.tsv', 'train_source3.tsv']:
        with open(os.path.join(train_dir, src), 'r', encoding='utf-8') as f:
            next(f)
            for line in f:
                p = line.rstrip('\n').split('\t')
                if p[0] in needed_cand:
                    cand_dict[p[0]] = (
                        p[1] if len(p) > 1 else '',
                        p[2] if len(p) > 2 else '',
                        p[3] if len(p) > 3 else ''
                    )
    print(f"   -> Attributes loaded in {time.time()-t0:.2f}s ({len(s1_dict):,} S1, {len(cand_dict):,} S2/S3).", flush=True)

    # Build DataFrame
    print("\n[4/5] Building pair dataset and labeling with Ground Truth...", flush=True)
    all_s1, all_cand, targets = [], [], []
    for s1, c2 in sample_pairs:
        if s1 in s1_dict and c2 in cand_dict:
            all_s1.append(s1)
            all_cand.append(c2)
            is_match = 1 if (s1 in gt_dict and c2 in gt_dict[s1]) else 0
            targets.append(is_match)

    pos_count = sum(targets)
    neg_count = len(targets) - pos_count
    print(f"   -> Labeled pairs: {len(targets):,} (True Matches: {pos_count:,}, Hard Negatives: {neg_count:,}, Match Ratio: {pos_count/len(targets)*100:.2f}%)", flush=True)

    df_pairs = pd.DataFrame({
        'id1': all_s1,
        'id2': all_cand,
        'name1': [s1_dict[x][0] for x in all_s1],
        'addr1': [s1_dict[x][1] for x in all_s1],
        'country1': [s1_dict[x][2] for x in all_s1],
        'name2': [cand_dict[x][0] for x in all_cand],
        'addr2': [cand_dict[x][1] for x in all_cand],
        'country2': [cand_dict[x][2] for x in all_cand],
        'target': targets
    })

    print(" Computing 16 vectorized similarity & disqualifier features...", flush=True)
    df_features = compute_features_fast(df_pairs)

    # 4. Train/Val Split within candidates
    unique_s1_list = list(set(df_features['id1']))
    random.seed(42)
    random.shuffle(unique_s1_list)
    split_idx = int(len(unique_s1_list) * 0.8)
    train_s1_set = set(unique_s1_list[:split_idx])
    val_s1_set = set(unique_s1_list[split_idx:])

    df_train = df_features[df_features['id1'].isin(train_s1_set)]
    df_val = df_features[df_features['id1'].isin(val_s1_set)]

    print(f"   -> Train set: {len(df_train):,} pairs ({len(train_s1_set):,} entities)", flush=True)
    print(f"   -> Val set:   {len(df_val):,} pairs ({len(val_s1_set):,} entities)", flush=True)

    X_train = df_train[FEATURE_COLUMNS]
    y_train = df_train['target']
    X_val = df_val[FEATURE_COLUMNS]
    y_val = df_val['target']

    train_data = lgb.Dataset(X_train, label=y_train)
    val_data = lgb.Dataset(X_val, label=y_val, reference=train_data)

    params = {
        'objective': 'binary',
        'metric': 'binary_logloss',
        'boosting_type': 'gbdt',
        'learning_rate': 0.08,
        'num_leaves': 63,
        'feature_fraction': 0.85,
        'bagging_fraction': 0.85,
        'bagging_freq': 5,
        'scale_pos_weight': 0.35, # Precision-heavy weighting for F0.5
        'verbose': -1,
        'seed': 42
    }

    print("\n[5/5] Training LightGBM Booster...", flush=True)
    model = lgb.train(
        params,
        train_data,
        num_boost_round=250,
        valid_sets=[train_data, val_data],
        callbacks=[lgb.early_stopping(stopping_rounds=20, verbose=True)]
    )

    model.save_model(args.model_out)
    print(f" Model saved to {args.model_out}", flush=True)

    # Feature Importance
    print("\n Feature Importances (Gain):", flush=True)
    importances = sorted(zip(FEATURE_COLUMNS, model.feature_importance(importance_type='gain')), key=lambda x: x[1], reverse=True)
    for feat, imp in importances:
        print(f"   - {feat:30s}: {imp:10.2f}", flush=True)

    # 5. Threshold Grid Search on Validation Split for Optimal Macro F0.5
    print("\n" + "=" * 80, flush=True)
    print(" THRESHOLD GRID SEARCH TO MAXIMIZE MACRO F0.5", flush=True)
    print("=" * 80, flush=True)

    val_preds = model.predict(X_val)
    df_val_eval = df_val.copy()
    df_val_eval['prob'] = val_preds

    best_thresh = 0.5
    best_f05 = -1.0
    best_metrics = None

    thresholds = [0.20, 0.25, 0.30, 0.35, 0.40, 0.45, 0.50, 0.55, 0.60]
    val_s1_ids = list(val_s1_set)

    for t in thresholds:
        # Filter matches at threshold t with Injective 1-to-1 constraint
        matched_df = df_val_eval[df_val_eval['prob'] >= t]
        inj_df = matched_df.sort_values('prob', ascending=False).drop_duplicates(subset=['id2'], keep='first')
        pred_dict = defaultdict(list)
        for _, row in inj_df.iterrows():
            pred_dict[row['id1']].append(row['id2'])

        res = compute_macro_f05(gt_dict, pred_dict, s1_ids=val_s1_ids)
        print(f" Threshold: {t:.2f} | Macro F0.5: {res['macro_f05']:.4f} | Prec: {res['macro_precision']:.4f} | Rec: {res['macro_recall']:.4f}", flush=True)

        if res['macro_f05'] > best_f05:
            best_f05 = res['macro_f05']
            best_thresh = t
            best_metrics = res

    print("\n" + "=" * 80, flush=True)
    print(f" OPTIMAL THRESHOLD: {best_thresh:.2f} (Macro F0.5: {best_f05:.4f})", flush=True)
    print("=" * 80, flush=True)
    print_evaluation_report(best_metrics, title=f"VALIDATION PERFORMANCE AT OPTIMAL THRESHOLD {best_thresh:.2f}")

    print(f" TRAINING & EVALUATION COMPLETED IN {(time.time()-start_time)/60:.2f} MINUTES!", flush=True)

if __name__ == '__main__':
    main()
